# Generated by Django 3.2.5 on 2021-07-29 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='categories',
        ),
        migrations.AddField(
            model_name='institution',
            name='categories',
            field=models.ManyToManyField(to='charity.Category'),
        ),
    ]
